name: build

on: [push, pull_request]

jobs:
  build_nvtt:
    name: "${{matrix.os}}, ${{matrix.build_type}}"
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
        build_type:
          - debug
          - release
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v3
    - name: Configure build
      shell: bash
      run: |
        cmake . -DCMAKE_BUILD_TYPE=${{matrix.build_type}}
    - name: Build
      shell: bash
      run: |
        cmake --build . -j$(nproc)
